set -v
git pull
cd ../JSCover
git pull
cd ../JSCover2
git pull
cd ../JSCover-gh-pages
git pull origin gh-pages
cd ../JSCover-maven-plugin
git pull
cd ../JSCover-maven-test
git pull
cd ../JSCover-samples
git pull
cd ../JMonitaur
git pull
#cd ../rhino-jscover
#git pull
#cd ../rhino-jscover-repackaged
#git pull
#cd ../closure-compiler
#git pull
cd ../java8-tests
git pull
cd ../dotfiles
git pull
